name: "Don't Panic: Gadgets, the Internet, and You"
url: "http://dontpanic.io"
bucket: "http://s3.amazonaws.com/dontpanicpodcast"
pygments: true

live: true

author: "Colby Rabideau, Dan Miller & Shaun Jennings"

exclude:
  - README.md
